### PR TITLE
replace go-glib with gotk3/gotk3

### PR DESCRIPTION
**Pull request by RSWilli**
I wanted to use this PR as a base for discussion and to see if the github action would run through.

The point of this PR is the following: Why are we maintaining go-glib, when it was originally forked from [gotk3/gotk3](https://github.com/gotk3/gotk3) where it is better maintained by a lot more people?

This PR completely builds on my machine, and with issues such as #49 I hope that they were fixed in upstream in the last two years (!) since the glib bindings were last updated

### CODE REVIEW

**Comment by RSWilli** [comment]
I also found out that we are currently not building examples/minio and examples/websocketsrc in the action because they are separate modules

**Comment by tinyzimmer** [comment]
I wanted access to some stuff they weren't exporting. I also added quite a bit that makes the go plugins work correctly.

Other stuff is helpers for value transfer and ownership. But perhaps there is a middle ground where we get any critical features needed merged into them.

**Comment by tinyzimmer** [comment]
In fact. The entire foundation of the plugin system is built mostly into glib. It's where I basically implemented GObjects and Ginterfaces in go such that gstreamer's runtime would recognize and work with them.

**Comment by RSWilli** [comment]
@tinyzimmer I've discovered that blog entry before, good job!

I worked a bit more on this and as you said a lot broke. Although most is easy to fix (I hope) (e.g. `glib.TransferFull -> glib.AssumeOwnership`). The plugin system you described needs glib bindings not exported by gotk3. This system as a whole is pure magic to me (see #19) and I do not know if I can (or even want) to maintain it. I'll try a bit more.

Some of the functions used could be moved to go-gst, for others I will open a PR to gotk3 (assuming this PR works out in our favor)

For my personal use case of these bindings I do not need to write custom plugins, so I'd even consider dropping the support for them.

**Comment by tinyzimmer** [comment]
It's a very niche use case indeed.  At the time it was more a learning exercise than any actual production usage scenarios. That being said I _might_ just have one coming up for them. But I could also do without them. 

If we can get fully off the fork I'm all for it. But I'd still want to jump in and see if I can find a way to get plugins working either via self-contained additional bindings where needed in this repo, or perhaps a separate one.

**Comment by RSWilli** [comment]
@tinyzimmer let's try the following:

* first we get the github actions green again, however possible. I just forked gotk3 and tried to go.mod replace it but that didn't work...
* then we try to get the plugin stuff working again, or maybe talk about how we can handle them.

**Comment by sdroege** [comment]
I'd say it would be a pity to lose the support for writing new elements with the bindings. While I'm not using Go at all, in most GStreamer applications I write that are a bit more complex I end up writing custom elements (not plugins though). In most cases these could also be emulated with pad probes and the like but that would be more hacky and fragile.

**Comment by RSWilli** [comment]
@sdroege I see your point. I would also like to keep them, but I'd also like to keep the magic to a minimum.

**Comment by tinyzimmer** [comment]
I'm sorta in the camp of just "it's an awesome feature to support if it is practical to continue doing so."

I know there is a good chance it'll come down to me needing to dig in and fix them up for the latest changes. But I can't guarantee when I might be available to do that. I want to say maybe within a week or two, but I suck at those promises currently. 

So if it comes down to being the only blocker on getting off the native glib and yall wanna go ahead and push that change through. We still have the history. We can rip them out of here (or comment them out if you want to be super hacky) and I can get back into them when I have a chance. If anyone is using them out the in the wild they are likely pinned to a very old version anyway (but we should maybe make a disclaimer in a CHANGELOG).

**Comment by metal3d** [comment]
Hello, 

There's one thing that bothers me about using gotk3, and that's the dependency on GTK3 (obsolete, and above all useless). Here's a simple example. I use Fyne.io to create an interface and I successfully use go-gst. Fyne is a library that has no other needs than GLFW. It runs on Linux, Windows, Mac...

If you add a dependency to GTK, it will require an additional dependency for builds.

I understand that the Go-GLib library is a bit outdated, but using Gotk3 will make work more cumbersome for my projects, and certainly for others.

**Comment by RSWilli** [comment]
> If you add a dependency to GTK, it will require an additional dependency for builds.

We will not include a GTK3 dependency.

The [go mod file of gotk3](https://github.com/gotk3/gotk3/blob/master/go.mod) has no external dependencies and we will only depend on the glib subpackage. You will need GTK3 if you try to build one of the files that include the gtk3 C header file like the [gtk bindings](https://github.com/gotk3/gotk3/blob/master/gtk/gtk.go#L49)

**Comment by RSWilli** [comment]
@tinyzimmer I thought what @sdroege wrote and I think we should continue supporting custom elements.

If we want to support writing plugins is up to discussion IMHO.

**Comment by tinyzimmer** [comment]
> @tinyzimmer I thought what @sdroege wrote and I think we should continue supporting custom elements.
> 
> If we want to support writing plugins is up to discussion IMHO.

In my head, plugins and elements are one and the same, but maybe I'm mistaken?

**Comment by sdroege** [comment]
Plugins are (usually shared) libraries that provide an entry point for registering element (and typefind, device provider, etc) factories. You can have custom element (subclasses) and also element factories without providing an actual plugin.

Plugins are mostly for providing new functionality to multiple applications.

**Comment by tinyzimmer** [comment]
Ah well then we can probably assume that wherever I said plugins, I intended to say elements :smile:

**Comment by atishnazir** [comment]
Just chiming in here.  I echo the need for custom element support.  This last week I've had to write 3 custom elements.

Of course there is nothing stopping me from writing them as plugins in either C or Rust, but it was really nice to write them within the Go based project and statically register them for usage.

**Comment by RSWilli** [comment]
@atishnazir after fiddling around with custom elements yesterday I can definitely say that they are really useful and a good thing to have.

We can however improve the usability (e.g. splitting up the BinImpl interface)

**Comment by atishnazir** [comment]
I agree.  I've used go-gst to create both custom elements that I've statically registered within an application and plugins which I've installed on Linux (specifically an HTTP src that implements URI handler interface).

I'm a little uncomfortable about the GTK dependency as I mostly work on headless devices.  I've just spent a week tuning custom builds of GStreamer to minimise stuff I didn't need to get.

**Comment by RSWilli** [comment]
I'm closing this after some investigation in #61. gotk3 has the same issues: 

https://github.com/gotk3/gotk3/blob/655547b6cbbc2da7d962d2c234c28fb1fbc95b60/glib/glib.go#L1066

Converting to gotk3 wont fix segfaults, because they are doing the same kinds of invalid pointer castings, that are not fixable without a big breaking change

**Pull request closed without merging**
