### PR TITLE
add support for GstPromise

### PR DESCRIPTION
**Pull request by RSWilli**
add support for GstPromise, add a test to check if promise gets unreffed on GC properly

### CODE REVIEW

**Comment by RSWilli** [comment]
@nickeygit maybe take a look at the test here, it's not yet working, but an idea. (related to #109 )

The assert is missing something crucial I haven't figured out what exactly. I want to check that the pointers are invalid after GC runs.

**Comment by RSWilli** [comment]
I added a second test to check if the (un-) marshal works. I discovered that we need the concept of an initOnce for testing, because we need to init gstreamer but can't do it twice.

**Comment by sdroege** [comment]
Why can't you do it twice? There's nothing wrong with calling `gst_init()` twice

**Comment by RSWilli** [comment]
Maybe this is something for the testing issue. I tried to Init() and Deinit() for every test but gstreamer complained about the multiple Deinits. I just assumed that init would be also something that we should only do once.

**Comment by sdroege** [comment]
Yes you can only call `gst_deinit()` once, and nothing else from GStreamer afterwards (not even `gst_init()`). `gst_init()` can be called multiple times though

**Pull request merged**
