### PR TITLE
add a method to convert a GstPad to a GhostPad

### PR DESCRIPTION
**Pull request by RSWilli**

### CODE REVIEW

**Comment by neilyoung** [comment]
I can confirm this PR to work.  Thanks

**Comment by sdroege** [comment]
You might want to add some checks / assertions in here about the type, but also it would probably be good to have some general up/downcasting infrastructure :)

**Comment by RSWilli** [comment]
@sdroege in my app I hadn't stumbled upon a case where I needed to downcast. Upcasting is mostly supported out of the box because of the way the structs are embedded into each other.

The checks assertions you are talking about, will [these](https://github.com/go-gst/go-gst/blob/main/gst/gst.go.c#L5-L48) suffice? Or are there other methods that do these checks for us?

**Comment by sdroege** [comment]
> @sdroege in my app I hadn't stumbled upon a case where I needed to downcast.

Not when getting back a `GstElement` from `gst_parse_launch()` and having to cast it to a `GstPipeline` or `GstBin`, for example? Downcasting seems like a quite common thing to need :)

> The checks assertions you are talking about, will [these](https://github.com/go-gst/go-gst/blob/main/gst/gst.go.c#L5-L48) suffice? Or are there other methods that do these checks for us?

The `_CAST` variants of those macros don't do any checks at all, but the others do. I meant those, or something custom in your code that would cause a Go panic instead of a C `g_critical()` (plus `NULL` return which then will probably cause some non-descriptive Go panic somewhere?).

**Comment by RSWilli** [comment]
> Downcasting seems like a quite common thing to need :)

I get that this is useful, personally I don't use parse launch though. On top the only way to call `gst_parse_launch` through the bindings is [here](https://github.com/go-gst/go-gst/blob/b9552df57e7909f0f3ada3117b00aeef47f64a81/gst/gst_pipeline.go#L47) where the downcasting is handled internally (but without any checks).

> C g_critical() (plus NULL return ...)

I read from this that the type checking casts mentioned above return NULL if the cast is not valid? This would make it possible to raise an error in the go bindings (to panic would be unwise IMO).

Annother problem @neilyoung discovered is that we are currently unable to upcast while unmarhaling the values from a glib signal, e.g.:

```go
uriDecodeBin, err := gst.NewElement("uridecodebin")
if err != nil {
	return nil, err
}

uriDecodeBin.Connect("child-added", childAdded)


func childAdded(self *gst.Element, child *glib.Object, name string) {
	InfoLog.Println("child-added", name)
	if strings.Contains(name, "decodebin") {
		child.Connect("child-added", childAdded)
	}
}
```

This currently panics, because the added child is not always a `*glib.Object`, but anything that extends it.

**Comment by sdroege** [comment]
> I read from this that the type checking casts mentioned above return NULL if the cast is not valid? This would make it possible to raise an error in the go bindings (to panic would be unwise IMO).

A proper error would be even better, but a panic would be better than no checks at all ;)

> where the downcasting is handled internally (but without any checks).

That's also wrong because it doesn't necessarily return a pipeline. It depends on how it's called.

> that we are currently unable to upcast while unmarhaling the values from a glib signal

That's also downcasting. Same problem in a different color really :)

**Comment by RSWilli** [comment]
I realized that I need to think about this more, I will open an issue but not merge this one. In the stable bindings casting can be done by wrapping and unwrapping the structs, but not yet with any safety guarantees.

**Comment by neilyoung** [comment]
OK, no problem. Thanks for your patience

**Pull request closed without merging**
